public class Main {
    public static void main(String[] args) {
        LinkedListDouble buatlagu = new LinkedListDouble();

        buatlagu.add("Billy Joel", "Piano Man", "Folk", 1973, 5,39);
        buatlagu.add("Bruno Mars dan Lady Gaga", "Die With A SWmile", "pop", 2024, 4,11);
        buatlagu.add("Feast", "Nina", "Indonesian Rock", 2024, 4,37);
        buatlagu.add("Wave to Earth", "Bad", "Korean Rock, thai indie", 2023, 4,24);
        buatlagu.add("Why don't we", "8 Latter", "Pop", 2018, 3,10);
        buatlagu.add("The Smiths", "There is a light that never goes out", "Pop", 1986, 4,4);
        buatlagu.add("Pamungkas", "To The Bone", "Indonesian Indie", 2020, 5,44);
        buatlagu.add("One Ok Rock", "We Are", "Pop Rock", 2018, 4,15);
        buatlagu.add("Le Young ji", "Small Girl", "R&B", 2024, 3,9);
        buatlagu.add("Green Day", "21 Guns", "Punk Pop", 2009, 5,21);
        buatlagu.add("Selena Gomez", "Lose You to Love Me", "Pop", 2019, 3, 27);
        buatlagu.add("Camila Cabello", "Havana", "Pop", 2017, 3, 36);
        buatlagu.add("Maroon 5", "Sugar", "Pop", 2014, 3, 55);
        buatlagu.add("The Chainsmokers", "Closer", "EDM", 2016, 4, 4);
        buatlagu.add("Avicii", "Wake Me Up", "EDM", 2013, 4, 7);
        buatlagu.add("Zedd", "Clarity", "EDM", 2012, 4, 31);
        buatlagu.add("David Guetta", "Titanium", "EDM", 2011, 4, 5);
        buatlagu.add("Daft Punk", "Get Lucky", "Funk", 2013, 6, 7);
        buatlagu.add("Sia", "Chandelier", "Pop", 2014, 3, 36);
        buatlagu.add("Katy Perry", "Firework", "Pop", 2010, 3, 47);
        buatlagu.add("Rihanna", "Diamonds", "Pop", 2012, 3, 45);
        buatlagu.add("Kendrick Lamar", "HUMBLE.", "Hip Hop", 2017, 2, 57);
        buatlagu.add("Jay-Z", "Empire State of Mind", "Hip Hop", 2009, 4, 36);

        buatlagu.add("Led Zeppelin", "Immigrant Song", "Rock", 1970, 2, 26);
        buatlagu.add("Elton John", "Tiny Dancer", "Soft Rock", 1971, 6, 12);
        buatlagu.add("The Rolling Stones", "Angie", "Rock", 1972, 4, 33);
        buatlagu.add("Stevie Wonder", "Superstition", "Funk", 1972, 4, 26);
        buatlagu.add("Queen", "Bohemian Rhapsody", "Rock", 1975, 5, 55);
        buatlagu.add("ABBA", "Dancing Queen", "Pop", 1976, 3, 52);
        buatlagu.add("Bee Gees", "Stayin' Alive", "Disco", 1977, 4, 45);
        buatlagu.add("The Clash", "London Calling", "Punk Rock", 1979, 3, 19);
        buatlagu.add("Michael Jackson", "Billie Jean", "Pop", 1982, 4, 54);
        buatlagu.add("Prince", "Purple Rain", "Rock", 1984, 8, 41);
        buatlagu.add("Bon Jovi", "Livin' on a Prayer", "Rock", 1986, 4, 11);
        buatlagu.add("U2", "With or Without You", "Rock", 1987, 4, 55);
        buatlagu.add("Guns N' Roses", "Sweet Child o' Mine", "Rock", 1987, 5, 56);
        buatlagu.add("Metallica", "One", "Heavy Metal", 1988, 7, 24);
        buatlagu.add("Nirvana", "Smells Like Teen Spirit", "Grunge", 1991, 5, 1);
        buatlagu.add("Red Hot Chili Peppers", "Under the Bridge", "Alternative Rock", 1992, 4, 24);
        buatlagu.add("Dr. Dre", "Nuthin' but a 'G' Thang", "Hip Hop", 1992, 3, 58);
        buatlagu.add("Radiohead", "Creep", "Alternative Rock", 1993, 3, 58);
        buatlagu.add("Oasis", "Wonderwall", "Britpop", 1995, 4, 18);
        buatlagu.add("2Pac", "California Love", "Hip Hop", 1995, 6, 25);
        buatlagu.add("The Notorious B.I.G.", "Hypnotize", "Hip Hop", 1997, 3, 50);
        buatlagu.add("Blink-182", "All the Small Things", "Pop Punk", 1999, 2, 48);
        buatlagu.add("Eminem", "Stan", "Hip Hop", 2000, 6, 44);
        buatlagu.add("OutKast", "Ms. Jackson", "Hip Hop", 2000, 4, 30);
        buatlagu.add("Linkin Park", "In the End", "Nu Metal", 2001, 3, 36);
        buatlagu.add("The White Stripes", "Seven Nation Army", "Rock", 2003, 3, 51);
        buatlagu.add("Green Day", "Boulevard of Broken Dreams", "Rock", 2004, 4, 20);
        buatlagu.add("Coldplay", "Fix You", "Alternative Rock", 2005, 4, 55);
        buatlagu.add("Arctic Monkeys", "I Bet You Look Good on the Dancefloor", "Indie Rock", 2006, 2, 53);
        buatlagu.add("Amy Winehouse", "Rehab", "Soul", 2006, 3, 33);
        buatlagu.add("Rihanna", "Umbrella", "Pop", 2007, 4, 36);
        buatlagu.add("Kings of Leon", "Sex on Fire", "Rock", 2008, 3, 23);
        buatlagu.add("Beyoncé", "Single Ladies (Put a Ring on It)", "Pop", 2008, 3, 13);
        buatlagu.add("Jay-Z", "Empire State of Mind", "Hip Hop", 2009, 4, 36);
        buatlagu.add("Lady Gaga", "Bad Romance", "Pop", 2009, 4, 54);
        buatlagu.add("Adele", "Rolling in the Deep", "Pop", 2010, 3, 48);
        buatlagu.add("Kanye West", "Runaway", "Hip Hop", 2010, 9, 8);
        buatlagu.add("Bruno Mars", "Just the Way You Are", "Pop", 2010, 3, 40);
        buatlagu.add("Gotye", "Somebody That I Used to Know", "Alternative", 2011, 4, 4);
        buatlagu.add("Lana Del Rey", "Video Games", "Indie Pop", 2011, 4, 42);
        buatlagu.add("Imagine Dragons", "Radioactive", "Alternative Rock", 2012, 3, 6);
        buatlagu.add("Macklemore & Ryan Lewis", "Thrift Shop", "Hip Hop", 2012, 3, 55);
        buatlagu.add("Daft Punk", "Get Lucky", "Disco", 2013, 6, 9);
        buatlagu.add("Pharrell Williams", "Happy", "Pop", 2013, 3, 53);
        buatlagu.add("Ed Sheeran", "Thinking Out Loud", "Pop", 2014, 4, 41);
        buatlagu.add("Taylor Swift", "Shake It Off", "Pop", 2014, 3, 39);
        buatlagu.add("The Weeknd", "Can't Feel My Face", "R&B", 2015, 3, 35);
        buatlagu.add("Justin Bieber", "Sorry", "Pop", 2015, 3, 20);
        buatlagu.add("Kendrick Lamar", "HUMBLE.", "Hip Hop", 2017, 2, 57);
        buatlagu.add("Billie Eilish", "Bad Guy", "Pop", 2019, 3, 14);

        buatlagu.add("Prince", "Purple Rain", "Rock", 1984, 8, 41);
        buatlagu.add("Kanye West", "Runaway", "Hip Hop", 2010, 9, 8);
        buatlagu.add("Metallica", "One", "Heavy Metal", 1988, 7, 24);
        buatlagu.add("Eminem", "Stan", "Hip Hop", 2000, 6, 44);
        buatlagu.add("Daft Punk", "Get Lucky", "Disco", 2013, 6, 9);
        buatlagu.add("2Pac", "California Love", "Hip Hop", 1995, 6, 25);
        buatlagu.add("Elton John", "Tiny Dancer", "Soft Rock", 1971, 6, 12);
        buatlagu.add("Adele", "Rolling in the Deep", "Pop", 2010, 3, 48);
        buatlagu.add("OutKast", "Ms. Jackson", "Hip Hop", 2000, 4, 30);
        buatlagu.add("Lana Del Rey", "Video Games", "Indie Pop", 2011, 4, 42);
        buatlagu.add("Beyoncé", "Single Ladies (Put a Ring on It)", "Pop", 2008, 3, 13);
        buatlagu.add("Lady Gaga", "Bad Romance", "Pop", 2009, 4, 54);
        buatlagu.add("Bee Gees", "Stayin' Alive", "Disco", 1977, 4, 45);
        buatlagu.add("The Weeknd", "Can't Feel My Face", "R&B", 2015, 3, 35);
        buatlagu.add("Justin Bieber", "Sorry", "Pop", 2015, 3, 20);
        buatlagu.add("Rihanna", "Umbrella", "Pop", 2007, 4, 36);
        buatlagu.add("Jay-Z", "Empire State of Mind", "Hip Hop", 2009, 4, 36);
        buatlagu.add("Led Zeppelin", "Immigrant Song", "Rock", 1970, 2, 26);
        buatlagu.add("Green Day", "Boulevard of Broken Dreams", "Rock", 2004, 4, 20);
        buatlagu.add("Coldplay", "Fix You", "Alternative Rock", 2005, 4, 55);
        buatlagu.add("Bon Jovi", "Livin' on a Prayer", "Rock", 1986, 4, 11);
        buatlagu.add("The Rolling Stones", "Angie", "Rock", 1973, 4, 33);
        buatlagu.add("The Clash", "London Calling", "Punk Rock", 1979, 3, 19);
        buatlagu.add("Michael Jackson", "Billie Jean", "Pop", 1982, 4, 54);
        buatlagu.add("Queen", "Bohemian Rhapsody", "Rock", 1975, 5, 55);
        buatlagu.add("The Notorious B.I.G.", "Hypnotize", "Hip Hop", 1997, 3, 50);
        buatlagu.add("Arctic Monkeys", "I Bet You Look Good on the Dancefloor", "Indie Rock", 2006, 2, 53);
        buatlagu.add("Gotye", "Somebody That I Used to Know", "Alternative", 2011, 4, 4);
        buatlagu.add("Imagine Dragons", "Radioactive", "Alternative Rock", 2012, 3, 6);
        buatlagu.add("U2", "With or Without You", "Rock", 1987, 4, 55);
        buatlagu.add("Bruno Mars", "Just the Way You Are", "Pop", 2010, 3, 40);
        buatlagu.add("Taylor Swift", "Shake It Off", "Pop", 2014, 3, 39);
        buatlagu.add("Guns N' Roses", "Sweet Child o' Mine", "Rock", 1987, 5, 56);
        buatlagu.add("Radiohead", "Creep", "Alternative Rock", 1993, 3, 58);
        buatlagu.add("Oasis", "Wonderwall", "Britpop", 1995, 4, 18);
        buatlagu.add("Nirvana", "Smells Like Teen Spirit", "Grunge", 1991, 5, 1);
        buatlagu.add("ABBA", "Dancing Queen", "Pop", 1976, 3, 52);
        buatlagu.add("Red Hot Chili Peppers", "Under the Bridge", "Alternative Rock", 1992, 4, 24);
        buatlagu.add("Dr. Dre", "Nuthin' but a 'G' Thang", "Hip Hop", 1992, 3, 58);
        buatlagu.add("Kings of Leon", "Sex on Fire", "Rock", 2008, 3, 23);
        buatlagu.add("Amy Winehouse", "Rehab", "Soul", 2006, 3, 33);
        buatlagu.add("Kendrick Lamar", "HUMBLE.", "Hip Hop", 2017, 2, 57);
        buatlagu.add("Blink-182", "All the Small Things", "Pop Punk", 1999, 2, 48);
        buatlagu.add("Linkin Park", "In the End", "Nu Metal", 2001, 3, 36);
        buatlagu.add("Macklemore & Ryan Lewis", "Thrift Shop", "Hip Hop", 2012, 3, 55);
        buatlagu.add("Pharrell Williams", "Happy", "Pop", 2013, 3, 53);
        buatlagu.add("Ed Sheeran", "Thinking Out Loud", "Pop", 2014, 4, 41);
        buatlagu.add("Billie Eilish", "Bad Guy", "Pop", 2019, 3, 14);

        buatlagu.add("Coldplay", "Fix You", "Alternative Rock", 2005, 4, 55);
        buatlagu.add("Adele", "Rolling in the Deep", "Pop", 2010, 3, 48);
        buatlagu.add("Nirvana", "Smells Like Teen Spirit", "Grunge", 1991, 5, 1);
        buatlagu.add("Taylor Swift", "Shake It Off", "Pop", 2014, 3, 39);
        buatlagu.add("Guns N' Roses", "Sweet Child o' Mine", "Rock", 1987, 5, 56);
        buatlagu.add("Daft Punk", "Get Lucky", "Disco", 2013, 6, 9);
        buatlagu.add("Imagine Dragons", "Radioactive", "Alternative Rock", 2012, 3, 6);
        buatlagu.add("Beyoncé", "Single Ladies (Put a Ring on It)", "Pop", 2008, 3, 13);
        buatlagu.add("Amy Winehouse", "Rehab", "Soul", 2006, 3, 33);
        buatlagu.add("Led Zeppelin", "Immigrant Song", "Rock", 1970, 2, 26);
        buatlagu.add("U2", "With or Without You", "Rock", 1987, 4, 55);
        buatlagu.add("OutKast", "Ms. Jackson", "Hip Hop", 2000, 4, 30);
        buatlagu.add("Arctic Monkeys", "I Bet You Look Good on the Dancefloor", "Indie Rock", 2006, 2, 53);
        buatlagu.add("Michael Jackson", "Billie Jean", "Pop", 1982, 4, 54);
        buatlagu.add("Prince", "Purple Rain", "Rock", 1984, 8, 41);
        buatlagu.add("Lana Del Rey", "Video Games", "Indie Pop", 2011, 4, 42);
        buatlagu.add("Jay-Z", "Empire State of Mind", "Hip Hop", 2009, 4, 36);
        buatlagu.add("Radiohead", "Creep", "Alternative Rock", 1993, 3, 58);
        buatlagu.add("Blink-182", "All the Small Things", "Pop Punk", 1999, 2, 48);
        buatlagu.add("Queen", "Bohemian Rhapsody", "Rock", 1975, 5, 55);
        buatlagu.add("Pharrell Williams", "Happy", "Pop", 2013, 3, 53);
        buatlagu.add("Eminem", "Stan", "Hip Hop", 2000, 6, 44);
        buatlagu.add("Red Hot Chili Peppers", "Under the Bridge", "Alternative Rock", 1992, 4, 24);
        buatlagu.add("Rihanna", "Umbrella", "Pop", 2007, 4, 36);
        buatlagu.add("Gotye", "Somebody That I Used to Know", "Alternative", 2011, 4, 4);

        buatlagu.display();

        System.out.println("\nMengurutkan berdasarkan durasi (Bubble Sort):");
        long startTimeBubbleSort = System.nanoTime();
        buatlagu.bubbleSort();
        long endTimeBubbleSort = System.nanoTime();
        buatlagu.display();
        System.out.println("Waktu eksekusi Bubble Sort: " + (endTimeBubbleSort - startTimeBubbleSort) + " nanoseconds");

        System.out.println("\nMengurutkan berdasarkan tahun (Selection Sort):");
        long startTimeSelectionSort = System.nanoTime();
        buatlagu.selectionSort();
        long endTimeSelectionSort = System.nanoTime();
        buatlagu.display();
        System.out.println("Waktu eksekusi Selection Sort: " + (endTimeSelectionSort - startTimeSelectionSort) + " nanoseconds");

        buatlagu.displaysearch("21 Guns");

    }
}